# コンテナの動かし方を設定
services:
  # サービスの名前はなんでもいい
  game-server:
    # 同じフォルダのDockerfileを使用する
    build: .
    # ポートの設定
    # 左->外からアクセスするポート番号
    # 右->コンテナ内で使っているポート番号
    # localhost:8765でコンテナにアクセスできる
    ports:
      - "8765:8765"
    # サービスがクラッシュしたら
    # 自動で再起動する
    # ただし、手動で停止した場合は再起動しない
    restart: unless-stopped